name: Fork News
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  fork-news:
    runs-on: ubuntu-latest
    name: Sync with parent repository
    steps:
      - id: fork-news-sync
        uses: vitornovictor/fork-news@v1.0.0
        with:
          from-branch: main
          to-branch: main
          access-token: ${{ secrets.FORK_NEWS_TOKEN }}
