name: Sync Fork

on:
  schedule:
    - cron: '* */24 * * *' # every 30 minutes
  workflow_dispatch: # on button click

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v1.4
        with:
          owner: craigary
          base: main
          head: main
